version: '3'
services: 
  app:
    container_name: rpod-node-mongo
    restart: always
    build: .
    ports:
      - '80:8081'
    environment:
      - GRAPHQL_URL='http://127.0.0.1:80/graphql'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'