name: Node.js/Vue.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    
#     strategy:
#       matrix:
#         node-version: [10.x, 12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: NPM Install
        run: |
          npm install
      - name: Production build
        run: |
          npm run build
      - name: log content
        run: |
          ls
      - name:  Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_ACCESS_KEY}}
          AWS_REGION: ${{secrets.AWS_REGION}}
          AWS_S3_BUCKET:  ${{secrets.AWS_BUCKET}}
          # Directory of github to sync, use '.' for the entire repository
          SOURCE_DIR: "client/dist"
